name: personal_portofolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.9.1
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tech-stack/
    - assets/images/achievements/
    - assets/images/experience/
    - assets/images/projects/

  fonts:
    - family: "Roboto"
      fonts: 
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
